# Generated by Django 4.2.3 on 2023-07-27 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modification_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
    ]
