# Generated by Django 4.2.3 on 2023-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=1, max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
